import random

# Server settings
HOST = '127.0.0.1'
PORT = 1234
CLIENT_LIMIT = 50
GUID_LENGTH = 4

# Testing settings
ENABLE_SPAM_TESTING = False
TESTING_CLIENTS_COUNT = 3

# Message Settings
PRIVATE_MESSAGE_PREFIX_SIGN = ">"


def get_random_name():
    return EXAMPLE_NAMES[random.randint(0, len(EXAMPLE_NAMES) - 1)]


EXAMPLE_NAMES = [
    "Emma",
    "Liam",
    "Olivia",
    "Noah",
    "Ava",
    "Elijah",
    "Isabella",
    "William",
    "Sophia",
    "James",
    "Charlotte",
    "Benjamin",
    "Amelia",
    "Lucas",
    "Mia",
    "Henry",
    "Harper",
    "Alexander",
    "Evelyn",
    "Michael",
    "Abigail",
    "Daniel",
    "Emily",
    "Matthew",
    "Elizabeth",
    "Jackson",
    "Mila",
    "Logan",
    "Ella",
    "David",
    "Avery",
    "Joseph",
    "Sofia",
    "Samuel",
    "Camila",
    "Sebastian",
    "Scarlett",
    "Carter",
    "Victoria",
    "Wyatt",
    "Luna",
    "Jayden",
    "Grace",
    "John",
    "Chloe",
    "Owen",
    "Penelope",
    "Dylan",
    "Layla",
    "Luke",
    "Riley",
    "Gabriel",
    "Zoey",
    "Anthony",
    "Nora",
    "Isaac",
    "Lily",
    "Grayson",
    "Hannah",
    "Jack",
    "Zoe",
    "Julian",
    "Lillian",
    "Levi",
    "Addison",
    "Christopher",
    "Ellie",
    "Joshua",
    "Stella",
    "Andrew",
    "Natalie",
    "Lincoln",
    "Violet",
    "Mateo",
    "Aurora",
    "Ryan",
    "Savannah",
    "Jaxon",
    "Audrey",
    "Nathan",
    "Brooklyn",
    "Aaron",
    "Bella",
    "Isaiah",
    "Claire",
    "Thomas",
    "Skylar",
    "Charles",
    "Lucy",
    "Caleb",
    "Paisley",
    "Josiah",
    "Everly",
    "Christian",
    "Anna",
    "Hunter",
    "Caroline",
    "Eli",
    "Nova",
    "Jonathan",
    "Genesis",
    "Connor",
    "Emilia",
]
